# Generated by Django 5.1 on 2025-06-12 19:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentorder',
            options={'verbose_name': 'Заказ на оплату', 'verbose_name_plural': 'Заказы на оплату'},
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='duration',
            field=models.IntegerField(default=1, help_text='Длительность подписки в месяцах (1, 3, 6, 12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Длительность (месяцы)'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='rrn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RRN'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='tariff_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('lite', 'Базовый'), ('standard', 'Стандартный'), ('standard2', 'Продвинутый'), ('standard3', 'Профессиональный'), ('premium', 'Неограниченный')], default='standard', max_length=20, verbose_name='Тип тарифа'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
