# Generated by Django 5.1 on 2025-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
