# Generated by Django 5.1 on 2025-02-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentorder_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='tariff_type',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('premium', 'Премиум')], default='standard', max_length=20),
        ),
    ]
