# Generated by Django 5.1 on 2025-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentorder_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='tariff_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('standard', 'Стандарт'), ('standard2', 'Стандарт 2'), ('premium', 'Премиум')], default='standard', max_length=20),
        ),
    ]
