# Generated by Django 5.1 on 2025-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentorder_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='tariff_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('lite', 'Lite'), ('standard', 'Стандарт'), ('standard2', 'Стандарт 2'), ('standard3', 'Стандарт 3'), ('premium', 'Премиум')], default='standard', max_length=20),
        ),
    ]
