# Generated by Django 5.1 on 2025-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentorder_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='tariff_type',
            field=models.CharField(choices=[('free', 'Беспла́тный'), ('lite', 'Базовый'), ('standard', 'Cтандартный'), ('standard2', 'Продвинутый'), ('standard3', 'Профессиональный'), ('premium', 'Неограниченный')], default='standard', max_length=20),
        ),
    ]
