# Generated by Django 5.1 on 2025-06-12 19:02Add commentMore actions

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='chip_label',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='model',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Номер запчасти'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['brand'], name='warehouse_p_brand_9684eb_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['model'], name='warehouse_p_model_86051a_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['chip_label'], name='warehouse_p_chip_la_137fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['created_at'], name='warehouse_p_created_5f20e1_idx'),
        ),
    ]