# Generated by Django 5.1 on 2025-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_part_brand_alter_part_chip_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
