# Generated by Django 5.1 on 2025-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_part_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
