# Generated by Django 5.1 on 2024-08-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_profile_phone_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
