# Generated by Django 5.1 on 2025-02-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SearchRequest',
        ),
    ]
