# Generated by Django 5.1 on 2024-10-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_part_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='marking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
