# Generated by Django 5.1 on 2025-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_remove_searchrequest_user_delete_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Номер запчасти'),
        ),
    ]
