# Generated by Django 5.1 on 2025-04-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_part_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_number',
        ),
    ]
