# Generated by Django 5.1 on 2024-10-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_part_marking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='marking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
