# Generated by Django 5.1 on 2025-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_partview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
