# Generated by Django 5.1 on 2025-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_remove_part_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Номер запчасти'),
        ),
    ]
