# Generated by Django 5.1 on 2024-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts_images/'),
        ),
    ]
