# Generated by Django 5.1 on 2024-10-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_part_marking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='marking',
        ),
    ]
