# Generated by Django 5.1 on 2025-07-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_partview_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartView',
        ),
    ]
