# Generated by Django 5.1 on 2024-10-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_part_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/У')], default='new', max_length=10),
        ),
    ]
