# Generated by Django 5.1 on 2024-08-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_part_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='color_black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_brown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_gray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_pink',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_purple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='color_white',
            field=models.BooleanField(default=False),
        ),
    ]
