# Generated by Django 5.1 on 2024-10-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_part_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='condition',
        ),
    ]
