# Generated by Django 5.1 on 2024-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_remove_part_color_black_remove_part_color_blue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
