# Generated by Django 5.1 on 2024-10-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_remove_part_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='condition',
            field=models.CharField(choices=[('новое', 'Новое'), ('б/у', 'Б/У')], default='новое', max_length=10),
        ),
    ]
