# Generated by Django 5.1 on 2024-10-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_part_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
