# Generated by Django 5.1 on 2024-11-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_device_brand_model_parttype_partcondition_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='PartColor',
        ),
    ]
