# Generated by Django 5.1 on 2024-09-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_part_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='created_at',
        ),
    ]
