# Generated by Django 5.1 on 2024-11-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_rename_color_partcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='parttype',
            name='device',
        ),
        migrations.RemoveField(
            model_name='partcolor',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='partcondition',
            name='part_type',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='PartColor',
        ),
        migrations.DeleteModel(
            name='PartCondition',
        ),
        migrations.DeleteModel(
            name='PartType',
        ),
    ]
