# Generated by Django 5.1 on 2024-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_remove_model_brand_remove_parttype_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='chip_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
