# Generated by Django 5.1 on 2024-09-10 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_part_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 10, 7, 4, 30, 557491, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
