# Generated by Django 5.1 on 2024-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_part_chip_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='model',
            field=models.CharField(max_length=150),
        ),
    ]
