# Generated by Django 5.1 on 2024-12-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_part_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='model',
            field=models.CharField(max_length=200),
        ),
    ]
