# Generated by Django 5.1 on 2025-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_deleted_for_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_deleted_for_user2',
            field=models.BooleanField(default=False),
        ),
    ]
