# Generated by Django 5.1 on 2025-02-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_is_deleted_for_user1_chat_is_deleted_for_user2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_deleted_for_user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_deleted_for_user2',
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
