# Generated by Django 5.1 on 2025-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_chat_is_deleted_for_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='deleted_by_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='deleted_by_user2',
            field=models.BooleanField(default=False),
        ),
    ]
