# Generated by Django 5.1 on 2025-02-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_chat_deleted_by_user_chat_deleted_by_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='deleted_by_user1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='deleted_by_user2',
        ),
    ]
