# Generated by Django 5.1 on 2025-02-02 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_chat_deleted_by_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
