# Generated by Django 5.1 on 2025-02-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_chat_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_activity',
        ),
    ]
