# Generated by Django 5.1 on 2024-08-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
