# Generated by Django 5.1 on 2024-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_part_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='part_images/'),
        ),
    ]
