# Generated by Django 5.1 on 2024-08-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_part_color_black_part_color_blue_part_color_brown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='color_black',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_blue',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_brown',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_gold',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_gray',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_pink',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_purple',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_red',
        ),
        migrations.RemoveField(
            model_name='part',
            name='color_white',
        ),
    ]
