# Generated by Django 5.1 on 2024-08-31 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_part_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='colors',
        ),
    ]
