# """

#
# Generated by 'django-admin startproject' using Django 4.2.5.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """
# import os
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-8cdukni$6v87iktt)&++hbj7(2fldm0-9@px#fwth*ycmjz=7@'
#
# # SECURITY WARNING: don't run with debug turned on in production!
#


#
# # Application definition
#


#
# CRISPY_TEMPLATE_PACK = 'bootstrap4'  # Или 'bootstrap5', в зависимости от версии

#
# WSGI_APPLICATION = 'myproject.wsgi.application'
#
#
# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'sklad',       # Имя вашей базы данных
#         'USER': 'yura',        # Имя системного пользователя
#         'PASSWORD': '',        # Пароль не требуется для локальной работы
#         'HOST': 'localhost',   # Локальный сервер
#         'PORT': '5432',        # Порт по умолчанию
#     }
# }
#
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'django-app-db',
# #         'USER': 'admin',
# #         'PASSWORD': '12345678',
# #         'HOST': os.environ.get('DB_HOST'),
# #         'PORT': '5432',
# #     }
# # }
#
#
#
#

#
# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/
#

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
#
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/
#

#
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
#

#
#
#
#
#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-8cdukni$6v87iktt)&++hbj7(2fldm0-9@px#fwth*ycmjz=7@'

# DEBUG = False
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', '192.168.0.5']
# ALLOWED_HOSTS = ['127.0.0.1', '192.168.1.26']
LOGIN_URL = 'login'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'warehouse',
    'user_profile',
    'crispy_forms',
    'user_registration',
    'widget_tweaks',
    'custom_admin',
    'chat',
    'notifications',
    'tariff',
    'payments',
    'storages',
    'errors',
    'advertisements',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise для обслуживания статики
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Дополните, если требуется
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'warehouse.context_processors.counts',
                'notifications.context_processors.unread_notifications',
                'warehouse.context_processors.subscription_status',
                'advertisements.context_processors.active_advertisements',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sklad',
        'USER': 'yura',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Настройки для статических файлов
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGOUT_REDIRECT_URL = '/'

# --------------------------
# S3 Storage Settings для медиафайлов (фото)
# --------------------------
AWS_ACCESS_KEY_ID = "07d847f251ab915a0b94"              # Ваш Access Key ID
AWS_SECRET_ACCESS_KEY = "jplKti1izNopbASzCqdlVR47udlRi8jhKOQG9Udf"  # Ваш Secret Key
AWS_STORAGE_BUCKET_NAME = "parts-images"                 # Имя вашего bucket
AWS_S3_ENDPOINT_URL = "https://s3-minsk-dc2.cloud.mts.by"  # HTTPS-эндпоинт API S3

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'access_key': AWS_ACCESS_KEY_ID,
            'secret_key': AWS_SECRET_ACCESS_KEY,
            'bucket_name': AWS_STORAGE_BUCKET_NAME,
            'endpoint_url': AWS_S3_ENDPOINT_URL,
            'signature_version': 's3',
        },
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_FILE_OVERWRITE = False

# Формируем MEDIA_URL для доступа к файлам через веб
MEDIA_URL = "https://s3-website-minsk-dc2.cloud.mts.by/parts-images/"

# --------------------------
# Email Settings
# --------------------------
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.mail.ru'
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True
# EMAIL_HOST_USER = '9604871@mail.ru'
# EMAIL_HOST_PASSWORD = 'j4Cy2rgYCj70K6SWcnU3'
# DEFAULT_FROM_EMAIL = '9604871@mail.ru'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'mobirazbor@mail.ru'
EMAIL_HOST_PASSWORD = 'j4Cy2rgYCj70K6SWcnU3'
DEFAULT_FROM_EMAIL = 'mobirazbor@mail.ru'
