# Generated by Django 5.1 on 2025-04-14 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='warehouse.part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало подписки')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки')),
                ('phone', models.CharField(max_length=15)),
                ('region', models.CharField(blank=True, choices=[('Минская область', 'Минская область'), ('Гомельская область', 'Гомельская область'), ('Гродненская область', 'Гродненская область'), ('Брестская область', 'Брестская область'), ('Могилевская область', 'Могилевская область'), ('Витебская область', 'Витебская область')], max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('workshop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_methods', models.TextField(blank=True, max_length=300, null=True)),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления')),
                ('tariff', models.CharField(choices=[('free', 'Беспла́тный'), ('lite', 'Базовый'), ('standard', 'Cтандартный'), ('standard2', 'Продвинутый'), ('standard3', 'Профессиональный'), ('premium', 'Неограниченный')], default='free', max_length=10, verbose_name='Тарифный план')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
