# Generated by Django 5.1 on 2024-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('Минская область', 'Минская область'), ('Гомельская область', 'Гомельская область'), ('Гродненская область', 'Гродненская область'), ('Брестская область', 'Брестская область'), ('Могилевская область', 'Могилевская область'), ('Витебская область', 'Витебская область')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
