# Generated by Django 5.1 on 2024-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_region_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
