# Generated by Django 5.1 on 2025-02-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
    ]
