# Generated by Django 5.1 on 2025-02-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_profile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tariff',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный')], default='free', max_length=10, verbose_name='Тарифный план'),
        ),
    ]
