# Generated by Django 5.1 on 2025-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало подписки'),
        ),
    ]
