# Generated by Django 5.1 on 2025-02-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_subscription_end_profile_subscription_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tariff',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('standard', 'Стандарт'), ('premium', 'Премиум')], default='free', max_length=10, verbose_name='Тарифный план'),
        ),
    ]
