# Generated by Django 5.1 on 2025-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_profile_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tariff',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('standard', 'Стандарт'), ('standard2', 'Стандарт 2'), ('premium', 'Премиум')], default='free', max_length=10, verbose_name='Тарифный план'),
        ),
    ]
