# Generated by Django 5.1 on 2025-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profile_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tariff',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('lite', 'Lite'), ('standard', 'Стандарт'), ('standard2', 'Стандарт 2'), ('standard3', 'Стандарт 3'), ('premium', 'Премиум')], default='free', max_length=10, verbose_name='Тарифный план'),
        ),
    ]
