# Generated by Django 5.1 on 2024-12-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_profile_delivery_methods_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shipping_methods',
            new_name='delivery_methods',
        ),
    ]
