# Generated by Django 5.1 on 2025-03-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_profile_receive_notifications_and_more'),
        ('warehouse', '0004_remove_searchrequest_user_delete_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='warehouse.part'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delivery_methods',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, choices=[('Минская область', 'Минская область'), ('Гомельская область', 'Гомельская область'), ('Гродненская область', 'Гродненская область'), ('Брестская область', 'Брестская область'), ('Могилевская область', 'Могилевская область'), ('Витебская область', 'Витебская область')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало подписки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tariff',
            field=models.CharField(choices=[('free', 'Беспла́тный'), ('lite', 'Базовый'), ('standard', 'Cтандартный'), ('standard2', 'Продвинутый'), ('standard3', 'Профессиональный'), ('premium', 'Неограниченный')], default='free', max_length=10, verbose_name='Тарифный план'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
