# Generated by Django 5.1 on 2024-12-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_rename_shipping_methods_profile_delivery_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='delivery_methods',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
