# Generated by Django 5.1 on 2025-01-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'JSON-редактор',
                'verbose_name_plural': 'JSON-редактор',
            },
        ),
    ]
