# Generated by Django 5.1 on 2025-03-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
    ]
