# Generated by Django 5.1 on 2025-02-15 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='broadcast_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
